// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using car_rent_backend.repository;

namespace car_rent_backend.Migrations
{
    [DbContext(typeof(ProjectContext))]
    [Migration("20210828153901_Added_Reservation_Entity")]
    partial class Added_Reservation_Entity
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.8")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("car_rent_backend.domain.Car", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Brand")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CarNr")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Class")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Cars");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Brand = "Peugeot",
                            CarNr = "1001",
                            Class = "Low",
                            Type = "Limousine"
                        },
                        new
                        {
                            Id = 2,
                            Brand = "Citroen",
                            CarNr = "1015",
                            Class = "Medium",
                            Type = "Minivan"
                        },
                        new
                        {
                            Id = 3,
                            Brand = "Chevrolet",
                            CarNr = "5075",
                            Class = "High",
                            Type = "Convertible"
                        },
                        new
                        {
                            Id = 4,
                            Brand = "VW",
                            CarNr = "1043",
                            Class = "Medium",
                            Type = "Limousine"
                        },
                        new
                        {
                            Id = 5,
                            Brand = "BMW",
                            CarNr = "9311",
                            Class = "Medium",
                            Type = "Convertible"
                        },
                        new
                        {
                            Id = 6,
                            Brand = "Suzuki",
                            CarNr = "1353",
                            Class = "High",
                            Type = "Minivan"
                        },
                        new
                        {
                            Id = 7,
                            Brand = "Tesla",
                            CarNr = "3197",
                            Class = "High",
                            Type = "Limousine"
                        },
                        new
                        {
                            Id = 8,
                            Brand = "VW",
                            CarNr = "4220",
                            Class = "Medium",
                            Type = "Minivan"
                        },
                        new
                        {
                            Id = 9,
                            Brand = "VW",
                            CarNr = "8314",
                            Class = "Low",
                            Type = "Limousine"
                        },
                        new
                        {
                            Id = 10,
                            Brand = "VW",
                            CarNr = "4750",
                            Class = "Low",
                            Type = "Limousine"
                        });
                });

            modelBuilder.Entity("car_rent_backend.domain.Customer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("City")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CustomerNr")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FirstName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Street")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Zip")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Customers");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            City = "St. Gallen",
                            CustomerNr = "C123",
                            FirstName = "Hans",
                            LastName = "Meier",
                            Street = "Turmstrasse 3",
                            Zip = 9000
                        },
                        new
                        {
                            Id = 2,
                            City = "Wil SG",
                            CustomerNr = "C463",
                            FirstName = "Jasmin",
                            LastName = "Hugentobler",
                            Street = "Im Tobel 19",
                            Zip = 9500
                        },
                        new
                        {
                            Id = 3,
                            City = "Appenzell",
                            CustomerNr = "C932",
                            FirstName = "Reto",
                            LastName = "Manser",
                            Street = "Bühlstrasse 18a",
                            Zip = 9050
                        },
                        new
                        {
                            Id = 4,
                            City = "St. Gallen",
                            CustomerNr = "C435",
                            FirstName = "Lukas",
                            LastName = "Heeb",
                            Street = "Hauptstrasse 50",
                            Zip = 9000
                        },
                        new
                        {
                            Id = 5,
                            City = "Lausanne",
                            CustomerNr = "N773",
                            FirstName = "Hanna",
                            LastName = "Muster",
                            Street = "Wurstweg 5",
                            Zip = 1000
                        });
                });

            modelBuilder.Entity("car_rent_backend.domain.Reservation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("CarClass")
                        .HasColumnType("int");

                    b.Property<int>("CustomerId")
                        .HasColumnType("int");

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsContract")
                        .HasColumnType("bit");

                    b.Property<string>("ReservationNr")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("datetime2");

                    b.Property<double?>("Total")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.HasIndex("CustomerId");

                    b.ToTable("Reservations");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CarClass = 1,
                            CustomerId = 1,
                            EndDate = new DateTime(2021, 8, 31, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsContract = true,
                            ReservationNr = "R123",
                            StartDate = new DateTime(2021, 8, 28, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Total = 400.0
                        },
                        new
                        {
                            Id = 2,
                            CarClass = 0,
                            CustomerId = 4,
                            EndDate = new DateTime(2021, 8, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsContract = true,
                            ReservationNr = "R884",
                            StartDate = new DateTime(2021, 8, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Total = 800.0
                        },
                        new
                        {
                            Id = 3,
                            CarClass = 1,
                            CustomerId = 2,
                            EndDate = new DateTime(2021, 8, 6, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsContract = true,
                            ReservationNr = "R241",
                            StartDate = new DateTime(2021, 8, 4, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Total = 300.0
                        },
                        new
                        {
                            Id = 4,
                            CarClass = 2,
                            CustomerId = 2,
                            EndDate = new DateTime(2021, 8, 28, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsContract = false,
                            ReservationNr = "R359",
                            StartDate = new DateTime(2021, 8, 20, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 5,
                            CarClass = 0,
                            CustomerId = 5,
                            EndDate = new DateTime(2021, 12, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsContract = false,
                            ReservationNr = "R305",
                            StartDate = new DateTime(2021, 12, 12, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 6,
                            CarClass = 2,
                            CustomerId = 2,
                            EndDate = new DateTime(2021, 9, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsContract = false,
                            ReservationNr = "R432",
                            StartDate = new DateTime(2021, 8, 31, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        });
                });

            modelBuilder.Entity("car_rent_backend.domain.Reservation", b =>
                {
                    b.HasOne("car_rent_backend.domain.Customer", "Customer")
                        .WithMany()
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Customer");
                });
#pragma warning restore 612, 618
        }
    }
}
