// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using car_rent_backend.repository;

namespace car_rent_backend.Migrations
{
    [DbContext(typeof(ProjectContext))]
    [Migration("20210725155149_Initial")]
    partial class Initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.8")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("car_rent_backend.domain.Customer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("City")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CustomerNr")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FirstName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Street")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Zip")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Customers");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            City = "St. Gallen",
                            CustomerNr = "C123",
                            FirstName = "Hans",
                            LastName = "Meier",
                            Street = "Turmstrasse 3",
                            Zip = 9000
                        },
                        new
                        {
                            Id = 2,
                            City = "Wil SG",
                            CustomerNr = "C463",
                            FirstName = "Jasmin",
                            LastName = "Hugentobler",
                            Street = "Im Tobel 19",
                            Zip = 9500
                        },
                        new
                        {
                            Id = 3,
                            City = "Appenzell",
                            CustomerNr = "C932",
                            FirstName = "Reto",
                            LastName = "Manser",
                            Street = "Bühlstrasse 18a",
                            Zip = 9050
                        },
                        new
                        {
                            Id = 4,
                            City = "St. Gallen",
                            CustomerNr = "C435",
                            FirstName = "Lukas",
                            LastName = "Heeb",
                            Street = "Hauptstrasse 50",
                            Zip = 9000
                        },
                        new
                        {
                            Id = 5,
                            City = "Lausanne",
                            CustomerNr = "N773",
                            FirstName = "Hanna",
                            LastName = "Muster",
                            Street = "Wurstweg 5",
                            Zip = 1000
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
